### ISSUE TITLE
[FR] Skip to next Unread feed (or none) when all items in specific feed marked as read

### ISSUE THREAD

**Issue by Kein** [Xyrio/RSSOwlnix#112]
What title says. When I open feed with just few items I can read it at a glance and decide there is nothing work checking so I press "Space" to "Mark all as read". Under the setup where I set to display "Unreal only" it will hide the feed source in the tree, but it will keep its tab with all feeds marked as read open, which makes no sense.

Suggestion: add an option that will force the view to skip to the next unread fee source in list after "Mark as Read" was invoked. Additionally, it would be nice if "Mark as Read" still work even all feeds in specific selected source were read - this way it can work as a quick shortcut to cycle through feed entries.

**Comment by Xyrio** [comment]
in menu under go / next are a bunch of cuntions that you can also set a key shortcut for. maybe those can also lighten your problem?

**Comment by Kein** [comment]
Nope, because let's say I have set to see only Unread feed categories and now I only have one category in the list. It has 5 new entries. If I press SPACE set to "Mark all as read" it will mark the read and REMOVED the category from the category tree, but it will keep open the news entries visible, except market as read.

**Comment by Xyrio** [comment]
if you do menu: `go / next / next feed` then that tab is reused and the next feed is shown. 
you can also press `ctrl + w` to close currently open tab.

so you you want it to be closed automatically.

if anyone wants to add such an option, send me a PR. i probably wont since one can just close the tab when wanted.
