### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Neustradamus** [Xyrio/RSSOwlnix#13]
Translations are missing since a long time, can you add?
A 2.1.2 was done with several packages: https://sourceforge.net/projects/rssowl/files/rssowl%202/2.1.2
But maybe better with one package + translations...

I see: https://github.com/Xyrio/RSSOwlnix-plugins-translation but there is not tutorial for add, can you create a documentation?

**Comment by Xyrio** [comment]
i have written on the release page about addons and translations. 2.5.0 has the same translations 2.2.1 had you can install them from menu. go Help / Install New Software... then choose the sie that ends with nls and you can select what you wish to install. it is not hard to figure out.

**Comment by Neustradamus** [comment]
I found a problem: if "Group items by category" is checked, the result is empty

**Comment by Xyrio** [comment]
btw 2.2.1 has translations you install them through the Tools / Language menu.

**Comment by Neustradamus** [comment]
I have added from the menu with "Group items by category" unckecked (it is checked by default)

**Comment by Xyrio** [comment]
yes you got it. so you are fine now? close this ticket then.

**Comment by Neustradamus** [comment]
It is not a problem of translations not complete.
By default for a research, we have an empty list -> the solution has been to uncheck the "Group items by category" which is checked by default.

**Comment by Xyrio** [comment]
yes i wrote that in the wiki.

**Comment by Neustradamus** [comment]
It is not possible to uncheck directly in the code: "Group items by category"

**Comment by Xyrio** [comment]
probably but it it might be simpler to add categories so one can leave that on.

**Comment by Neustradamus** [comment]
Of course!

**Comment by Xyrio** [comment]
translations are available as plugins.
