### ISSUE TITLE
accidental detach of tree tab; can't reattach

### ISSUE THREAD

**Issue by KamelittaOida** [Xyrio/RSSOwlnix#132]
I accidentally detached my tree tab and can't revert it back into tree/feed view.
do you happen to know the option in 

I tried to change my .opml file 
from
```
    <rssowl:pref id="instance/org.eclipse.ui.workbench/REUSE_OPEN_EDITORS_BOOLEAN" value="false" type="0" kind="1" />
    <rssowl:pref id="instance/org.eclipse.ui.workbench/REUSE_OPEN_EDITORS" value="5" type="1" kind="1" />
```
to (from weekly .opml)
```
    <rssowl:pref id="instance/org.eclipse.ui.workbench/REUSE_OPEN_EDITORS_BOOLEAN" value="true" type="0" kind="1" />
    <rssowl:pref id="instance/org.eclipse.ui.workbench/REUSE_OPEN_EDITORS" value="12" type="1" kind="1" />
```
and import the file but I get the following error:
I can't even import the weekly opml. same error

![image](https://user-images.githubusercontent.com/29007971/137336988-9f423d09-a7b0-4891-b814-16c2ec769845.png)

OS: win10
RSSOwlnix version: RSSOwlnix-2-9-0-win32.win32.x86_64.zip

**Comment by Xyrio** [comment]
you can drag it bag by using left click to drag the Feeds tab itself.

maybe if you deactivate hide existing it has something to import.

**Comment by KamelittaOida** [comment]
>you can drag it back by using left click to drag the Feeds tab itself. you

heh. that smart I was myself. this obviously didn't work 😅
there was no separator anymore. it was one full window/tab like the feeds. no split

didn't think about a new window. maybe ill try just to see what happens

thanks
