### ISSUE TITLE
"This browser is no longer supported"

### ISSUE THREAD

**Issue by dhry** [Xyrio/RSSOwlnix#134]
Trying to load https://twitter.com/gradydoctor/status/1349370631742234625 in the embedded browser, and I get:

**This browser is no longer supported.**
Please switch to a supported browser to continue using twitter.com. You can see a list of supported browsers in our Help Center. 

I have tried with the vmargs -DnoXulrunner parameter as well, same thing happens.

What is the embedded browser/version in RSSOwlnix, and is it possible to either update the engine or choose your own, in a way which opens actually within the RSSOwlnix window (rather than separate external window)?

OS: Windows 10 Enterprise 21H1
RSSOwlnix version: 2.9.0-beta

**Comment by Xyrio** [comment]
twitter has some tracking stuff that doesnt work correctly with embedded browser (IE on windows). use external browser. #62

**Comment by deepspaceaxolotl** [comment]
Getting this error on more and more sites as time passes. Is an update to the embedded browser or, better yet, a way to switch it out somehow as suggested and update it ourselves independently on the table?

(Thank you so much for the work on RSSOwlnix by the way, it's still the best RSS reader I've found (and has the best UI!) and I'm continually grateful that I can keep using it.)
