### ISSUE TITLE
Windows Install Instructions in the Wiki

### ISSUE THREAD

**Issue by shoulders** [Xyrio/RSSOwlnix#136]
I would like some instructions on how to install this software in Windows 10 because there is not installer which is what us Windows users are use to.

I am sure I will manage it but some recommendations such as which folder to place the files in, create a shortcut, how upgrades are managed.

On my Windows 10 x64 
- I will put my RSSOwlnix folder here C:\Program Files\RSSOwlnix
- I will manually create a shortcut in to my start menu
- I will import my old RSSOwl feeds using these instructions here: https://github.com/Xyrio/RSSOwlnix/releases and  https://github.com/Xyrio/RSSOwlnix/issues/89

I dont want to install chocolately at this time.

Some install instructions 
OS: Windows 10 x64 - Not installed yet

**Comment by Xyrio** [comment]
when a zip is provided it is up to the user where it is extracted to and if a shortcut is made or where the shortcut is put. rssowl is for more advanced users anyway. if a user cannot figure out how to unzip they are probably better of with another program.
