### ISSUE TITLE
Arrow Keys to Navigate Feeds

### ISSUE THREAD

**Issue by rammjet** [Xyrio/RSSOwlnix#143]
Linux Mint 20.3
RSSOwlnix 2.9.0 beta

When I click on the first feed in the list, the headlines are displayed on the right.  If I then use the down arrow to select the next feed, no headlines are shown on the right.  Only after I press Return do they appear.

This was working fine on Windows 10.  But in the back of my mind, I remember possibly doing something to enable this.

Are there any suggestions?

Thanks.

**Comment by Xyrio** [comment]
i tried a little and it only switches if feed is already opened in another tab. otherwise not. and it only switches if you wait for like a sec (to give you time to skip feeds).

**Comment by rammjet** [comment]
OK, I just booted up my Windows installation.  Using the arrow keys switches immediately.

BUT, it looks like it is an old version of the original RSSOwl:  2.2.1 from 2013-12-30.

**Comment by Xyrio** [comment]
well might have somehow changed then. i wont bother with it as it is a minor thing.

**Comment by rammjet** [comment]
OK, thanks.
