### ISSUE TITLE
Website or RSSOwlnix stopped working for specific FEED

### ISSUE THREAD

**Issue by RustKnight** [Xyrio/RSSOwlnix#144]
Hello Xyrio

I love your app and I do not want to change to something else. The way it looks and feels is super fresh.
I used it in the past for upwork freelance feed, but now while helping out a friend to set it up, it no longer manages to read the RSS file the website produces. 

If I try to import the rss file it says: " Unable to read the file as OPML. Results may be not accurate. "
I've searched for "flying stars" on the website for easier debug of the rss file. I had to rename it from "rss" to "rss.txt" to be able to attach it here on github. Originally it's just "rss" .

PS: if you're going to try to get an RSS file from upwork yourself, you'll need an account, other wise the RSS button won't appear.

Thank you for reading my request and I'm keeping my fingers crossed for a solution.

![image](https://user-images.githubusercontent.com/30659599/161602871-68f0cb23-bf80-493d-8ff0-6600e8752deb.png)

[rss.txt](https://github.com/Xyrio/RSSOwlnix/files/8412012/rss.txt)
.

**Comment by Xyrio** [comment]
you are importing wrong, the file is a rss feed not opml which is like a collection of links to feeds (and some other stuff).
`File - New - Feed` then
- if you want to add files use file:/// prefix like: file:///C:\Users\Carmen\Downloads\rss.txt
- if you want to add link use the usual http link
- there is also a shell:// to run programs/scripts that return the rss content on stdout (just fyi)

**Comment by RustKnight** [comment]
Is there a way I can donate to your project / or to you directly?
And if you also have a mail to contact you directly it would be great, I just have 1-2 questions that I would like to discuss in private. Thank you!

**Comment by Xyrio** [comment]
i dont take donations. if you cannot talk publicly about it, i dont want to talk about it.

**Comment by RustKnight** [comment]
Ok, no problem. 
I was going to nag you with further questions because I still didn't manage to make it work.

But now I figured it out. I needed to do these steps in order to get personalized feeds from Upwork into RSSOwlnix:

1. With Chrome, head to Upwork (best be singed in) and do a job search (Don't use Firefox, read below ***)
2. Click on the sign I show in the image (3 green wave signal like bars) and then click on RSS
3. A new page will open with a raw webpage showing a lot of code; copy the link of the newly opened page
4. Go in RSSOwlnix, click new and paste the link 
![image](https://user-images.githubusercontent.com/30659599/162591227-bacc8ed8-66e8-4eef-ba84-c087be9d016e.png)

*** I usually use Firefox, but in this case when I clicked on the feed sign, like I showed in step 2, it did not open a new page with the link. Instead it downloaded an RSS file which confused me in the first place.

After the given steps, the new Feed should now appear in the left panel with the give name.


@Xyrio Thank you for the time helping me out. Appreciate the work your doing! 

PS: don't always assume people have ill intents when trying to discuss with you in private ;)

**Comment by Xyrio** [comment]
importing the rss.txt works fine if you use file:/// prefix and absolute path. you would overwrite it with another download when you want to refresh it.

since you need to login to the site, you probably got a temporarily working link. it may be that the link wont work at some point in time.

**Comment by RustKnight** [comment]
I tried the file:/// method again now and I managed to make it work.
1. Should I use this method when creating feeds or the one I described above with Chrome? 

2. Sorry, but what do you mean by "overwrite it with another download when you want to refresh it." ?
I assumed feeds updated themselves periodically, but I think this is not what you meant to say. 
What do you mean by "when you want to refresh it"?

3. @Xyrio I noticed that some jobs are missing from the feed because they are visible only to signed in members.
I fixed this by going to passwords and adding to link the RSS link to it along with the Upwork credentials.
Now it shows all the jobs accordingly.

Is that the correct way to do it? And if I have various feeds, I need to manually go and add each one to the passwords section?
I feel like I'm doing something wrong. Either way, I'll do them manually if that's the case. I don't have that many to add.

**Comment by Xyrio** [comment]
for 1: yes, http links are usually how you do it when you can.

for 2. files you downloaded dont update themselves, you would have to redonwload to refresh it. only http links would get the latest automatically, since they point to the internet not to your harddrive.

for 3. if that works great.

adding the main site (the common part at the beginning that all rss from that site have) to the passwords section once should be enough. `https://www.upwork.com/`
