### ISSUE TITLE
javaw.exe is additionally started (task manager)

### ISSUE THREAD

**Issue by Neustradamus** [Xyrio/RSSOwlnix#15]
I use with Java 9 or 10 (x64 of course, no x86), I have:
- RSSOwlnix.exe
- javaw.exe

There was not 2 files with Java 8 (x64).
Can you look?

**Comment by Neustradamus** [comment]
2.2.1 with Java 8 (x86).... works without a javaw.exe

**Comment by Xyrio** [comment]
well java.exe shows console window and javaw.exe does not. you should always have both i think.

**Comment by Neustradamus** [comment]
No no, 2.2.1 do not add javaw.exe in taskmanager, only RSSOwl.exe (with real memory used).
I think there is an option to compile...

2.2.1+ has RSSOwlnix.exe with little memory used, less than 1mb) + javaw.exe with real memory used.

**Comment by Xyrio** [comment]
oh i see, i try java 10 but i dont think i can influence that.

**Comment by Neustradamus** [comment]
With Java 8 or 9, there is not?

**Comment by Xyrio** [comment]
tried it with jre 10 and it works. there is no javaw.exe or java.exe started at the same time. im on windows 7 64bit. whats your os?

**Comment by Xyrio** [comment]
you can get the packed jre 8 from here: 
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
file for 64bit is named: jre-8u161-windows-x64.tar.gz
then you need latest 7zip: https://www.7-zip.org/

**Comment by Neustradamus** [comment]
Tested on Windows 7 x64 with:
- last x64 version, old profile (.rssowl2 to .rssowlnix-beta) used since several years ago
- jre-10_windows-x64_bin.exe / http://www.oracle.com/technetwork/java/index.html

-> RSSOwlnix.exe + javaw.exe

**Comment by Neustradamus** [comment]
I have updated publications and with:
- jre-8u162-windows-x64.exe

-> RSSOwlnix.exe

The problem exists with Java 9 or 10, no problem with Java 8.

**Comment by Xyrio** [comment]
hmm that is weird. i am on win7 sp1 x64 too and as i posted above i get see no java exe even with jre9 and 10 from oracle

**Comment by Xyrio** [comment]
if you kill the javaw.exe does rssowlnix.exe quit too?

**Comment by Xyrio** [comment]
could you make a screenshot of what exactly you are seeing? i cannot reproduce this.

**Comment by Neustradamus** [comment]
Java 10 is unavailable now, no possibility to test again.

Have you success to see Java 11? https://www.oracle.com/technetwork/java/javase/downloads/index.html#JDK11

**Comment by Neustradamus** [comment]
I confirm that RSSOwnlnix 2.7.0 is launched perfectly with jdk-11.0.2_windows-x64_bin instead of jre-8uXXX-windows-x64.

Environment variable "Path":
- ;C:\Program Files\Java\jdk-11.0.2\bin
