### ISSUE TITLE
assertion failed: Could not find any Feed Set!

### ISSUE THREAD

**Issue by rambo919** [Xyrio/RSSOwlnix#150]
OS: MX Linux 21.2.1
RSSOwlnix version: RSSOwlnix-2-9-0-linux.gtk.x86_64
[log.zip](https://github.com/Xyrio/RSSOwlnix/files/10252020/log.zip)

Issue presents upon first "install". UI loads but can't import feeds.

**Comment by Xyrio** [comment]
java version 16 and higher does not work. try java 15.

**Comment by rambo919** [comment]
Switched to Open JDK 11 and it works now.
