### ISSUE TITLE
View panel is blank

### ISSUE THREAD

**Issue by rambo919** [Xyrio/RSSOwlnix#162]
OS: MX Linux 23.3 based on Debian 12.6
RSSOwlnix version:  RSSOwlnix-2.9 

Dunno if it's related but had to do an autoremove because there was almost a GB worth of unused packages..... and now I can't see anything. It's definitely there as indicated in the screenshot because you can click and drag the elements at which point they become visible.

Used adaptium to install JDK11 which is now the default and still does not work. Also deleted the .rssowlnix-beta folder (which too had become more than a GB due to bloating over age) and reimported from opml.

Are there specific dependencies that are unlisted? Because I can't find a list anywhere.
![Screenshot_20240803_120632](https://github.com/user-attachments/assets/a8c07615-fe5c-45ae-a13a-1774b9ea8e68)

**Comment by Joentjuh** [comment]
Not sure if this works for your situation, for me it was a webkit2gtk + nvidia issue.
Running with "WEBKIT_DISABLE_DMABUF_RENDERER=1" solved the issue, also works for liferea and tauri based applications. *https://gitlab.archlinux.org/archlinux/packaging/packages/webkit2gtk/-/issues/1

Either launch with: `WEBKIT_DISABLE_DMABUF_RENDERER=1 RSSOwlnix`
Or create/update the .desktop file: ".local/share/applications/RSSOwlnix.desktop"
[Desktop Entry]
Name=RSSOwlnix
Comment=RSSOwlnix
Type=Application
Icon=RSSOwlnix
Exec=env WEBKIT_DISABLE_DMABUF_RENDERER=1 RSSOwlnix
Categories=Qt;Network;News;
Terminal=false

**Comment by rambo919** [comment]
Yes this works
