### ISSUE TITLE
After cleaning feeds still marked (has sticky)

### ISSUE THREAD

**Issue by Newscp** [Xyrio/RSSOwlnix#22]
Hi,
i use "important marks" for some tags. After deleting them, cleaning and reopening rssowl again, the feeds are empty but the feed itself is still marked as important.

This iussue i encountered with the "orignal" version 2.4 an now, still with 2,5 beta.
OS 10, Java 1.8.172 64bit 

In my opion the "important flag" will not be cleaned correctly in the DB.

**Comment by Xyrio** [comment]
one can also create a search for sticky news (if it isnt already there) or only searching for read sticky news and making sure unread news are visible, then just unsticky or delete them manually.

**Comment by Newscp** [comment]
hi, you are right, these are marked as "sticky" ones. 
the feed itself is empty but the color doesn't change. 

if i unmark the news manually und delete it manually the feed stays uncolored.
but if i delete al sticky news, the feed will stay colored
![2018-10-04 11_54_12-keepass - rssowlnix](https://user-images.githubusercontent.com/39858868/46466694-46ce9680-c7cc-11e8-86be-9f4b14a06481.jpg)
![2018-10-04 11_54_01-kbs 931 in bayern _ fahrplananderungen - rssowlnix](https://user-images.githubusercontent.com/39858868/46466695-47672d00-c7cc-11e8-8b0f-1697fdaaaa9a.jpg)

**Comment by Xyrio** [comment]
as i wrote before. clean up does not remove sticky news so it will never change the color when you clean up.
you have to unsticky or delete manually to get rid of the color from the feed currently. 

if you have deleted all sticky news including unread ones the color does disappear. if color is still there you must still have sticky ones, maybe read and hidden?

**Comment by Newscp** [comment]
>
>
> as i wrote before. clean up does not remove sticky news so it will never change the color when you clean up.
> you have to unsticky or delete manually to get rid of the color from the feed currently.
> if you have deleted all sticky news including unread ones the color does disappear. if color is still there you must still have sticky ones, maybe read and hidden?
> fyi, auto delete for sticky does not exist.

I don't find any news in a sticky marked news. the filter says: show all news.
how do i find hidden news?


> you can alternatively to doing a search, create a filter for deleting sticky read news. but you have to run the filter manually every time you want to "clean up".
>
> instead of sticky you can
>
>     * use search(es)
>
>     * use filter(s) that moves stuff into newsbin(s)
>
>     * use filter(s) that sets label(s) (u can then also do a search for a specific label or use the existing "labeled news" search which uses "group by level" from the grouping menu at the top in the news list window)

in my filters ,i use "sticky news" an "open in browser". so it is very easy to me find and read important news.

i created a filter for deleting sticky news. it doesn't find any matches. if i clean up, the feed is still red.

if it is not possible to clean up empty news, i will use labels. but is a weired behavour.

**Comment by Xyrio** [comment]
by hidden i maent when you have set to show only unread news. if you have "show all news" than it is ok. that would show you read news that are sticky.

i wrote "clean up" in quoutes wanting to note that it is not the tools clean up functionality, you need to run the filter that deletes sticky news manually every time. i tested this and it works. it removes the color. just be carefull to only delete already read news. there is no undo for this. a saved search and manual delete is also an easy option but one that also allows you to verify what is deleted.

you could try to mark one news as sticky then unsticky it again. maybe the state was not updated somehow.

**Comment by Xyrio** [comment]
managed to reproduce somehow. needs fix.

**Comment by Newscp** [comment]
reproduce is very easy:
creat a feed
make a filter with "sticky note"
update feed
mark all news and delete them
clean up. and the feeds are still marked as sticky.

i have this behaviour on one windows 7 x64 maschine with java 1.8.181 x64
and on two windows 10 home and pro x64 maschines.  java 1.8.181 x64

**Comment by Neustradamus** [comment]
@newscp, can you try the soft with new Java builds?
https://www.oracle.com/technetwork/java/index.html
- Java SE 11 - Released 2018/09/25
- Java SE 10.0.2 - Released 2018/07/17
I have a problem: https://github.com/Xyrio/RSSOwlnix/issues/15
Thanks in advance.
