### ISSUE TITLE
Modify escaping problematic characters like Less-than sign and Ampersand

### ISSUE THREAD

**Issue by Ranulf83** [Xyrio/RSSOwlnix#23]
Is it possible to increase compatibility with rss feeds which for example misusing the ampersand ( & instead of & amp; ) by letting RSSOwlnix modify the invalid code of the feed to valid code?

> XML parsing error: <unknown>:5:44: not well-formed (invalid token)
`https://validator.w3.org/feed/docs/error/SAXError.html`

I know that a valid code would be the best solution, but this kind of modification would help alot witch invalid feeds.

**Anyway thanks for keeping RSSOwl alive.**

**Comment by Xyrio** [comment]
workaround:
since 2.8.0 one can use shell:// protocol to call external scripts that provide the rss content.
