### ISSUE TITLE
Hide reading part for have only contents list

### ISSUE THREAD

**Issue by Neustradamus** [Xyrio/RSSOwlnix#25]
Hide reading part for have only contents list

-> Like: "View -> Feeds"

**Comment by Xyrio** [comment]
that will completely hide it but you can just minimize it too.

**Comment by Neustradamus** [comment]
It is not possible to add in the menu to hide feed content?
Keep just only contents list?

There is a problem too: When we open a news of a feed, and we close the feed, later we open the feed again, the news is always opened... It will better to open nothing by default.

**Comment by Xyrio** [comment]
if you dont want the content window below the news list to disapear, choose in the news list menu "list" from "classic widescreen list newspaper headlines".

in preferences under View there is "never show more than X tabs" to prevent to many tabs.

**Comment by Neustradamus** [comment]
Oh yes for "list", it is perfect!

I have not "never show more than X tabs"...

**Comment by Xyrio** [comment]
Tool > Preferences > View > never show more than X tabs 
should be there

**Comment by Neustradamus** [comment]
Thanks :)
