### ISSUE TITLE
RSS Owlnix won't launch

### ISSUE THREAD

**Issue by cbinder4** [Xyrio/RSSOwlnix#27]
I'm sure it's probably me doing something wrong but I can not get RSS Owlnix to launch on Windows.  I get the splash screen as it attempts to load and then it errors and tells me to check the log file.  Attached is my latest log file.  Any assistance would be appreciated.
[1538856085097.log](https://github.com/Xyrio/RSSOwlnix/files/2453368/1538856085097.log)

**Comment by Xyrio** [comment]
what rssowlnix version are you using?

it is somehow not finding necessary classes (java binaries). i would try to rename the old install folder and rename (or copy and delete old one) home folder. then see if a fresh install works. you can then copy over the data from the renamed/copied home folder to like: %userprofile%\.rssowlnix-beta\.metadata\.plugins\org.rssowl.core\

**Comment by Xyrio** [comment]
the zip is the only "install".

**Comment by cbinder4** [comment]
I can't say why it didn't work the first time, but I deleted %userprofile%\.rssowlnix-beta and tried again and it is now working.  Thank you.
