### ISSUE TITLE
Chocolatey 

### ISSUE THREAD

**Issue by jgod** [Xyrio/RSSOwlnix#28]
Can we add this to [chocolatey](https://chocolatey.org/)?

**Comment by Xyrio** [comment]
if you want to feel free to do so.

**Comment by eargollo** [comment]
I have created a chocolatey package: https://chocolatey.org/packages/rssowlnix

Let me know if it works well.

**Comment by Xyrio** [comment]
have not tried it yet. 

i dont know how chocolately updates stuff but there is probably only one usecase you want to support for now: on update delete old install folder completely and install new one.

this is not perfect ( #5 ) but so far the easiest solution.

**Comment by eargollo** [comment]
I haven't tried update yet but installation is working really fine.

I will wait for you to release another version and as soon as I package it, I will verify if updates work.

If you release an official version (not beta), then the chocolatey package will also get to stable.

**Comment by eargollo** [comment]
Confirmed. Chocolatey upgrades are basically uninstalls and installs. It worked fine.

**Comment by jgod** [comment]
Thanks @eargollo for setting this up, I've not ever packaged something for it yet, I just use it alot (like many devs on Windows).

**Comment by jgod** [comment]
Just did an install and it picked up on my settings. Seems to work.

**Comment by eargollo** [comment]
I am glad it worked for you too :-)
The code for the choco install is at https://github.com/eargollo/choco-rssowlnix
I feel like we may need to update the description and metadata at https://github.com/eargollo/choco-rssowlnix/blob/master/rssowlnix.nuspec

**Comment by Xyrio** [comment]
#82
