### ISSUE TITLE
SourceForge feed authentication

### ISSUE THREAD

**Issue by taa1** [Xyrio/RSSOwlnix#3]
Hi,

I have a SourceForge feed that requires authentication, but I can't figure out how to trigger the necessary login dialog. I'm able to do File -> New -> Feed and put in the feed url and click NEXT, but when I click NEXT the feed name changes to, "SourceForge.net: Log In to SourceForge.net". If I click FINISH, then go to the feed -> Properties -> Status, it says, "The last attempt to load this feed failed. Reason: Invalid or Malformed Feed".

**Comment by Xyrio** [comment]
a concrete url to try this out would be useful.

could you try it with 2.2.1 if it also does not work there? (JCE patch works the same for 2.2.1)

**Comment by apstanley** [comment]
I think that it's an SSL handing issue in the code. I saw the same issue with https://sourceforge.net/blog/feed/ which is not authenticated. And I also saw the error with another authenticated site. I have 5 feeds, and the error occurs on two of them.

**Comment by taa1** [comment]
You can try [this link](https://sourceforge.net/p/ncid/discussion/devel/thread/df975b2a/feed.rss). I'll install 2.2.1 and let you know how it goes.

**Comment by Xyrio** [comment]
https://sourceforge.net/blog/feed/  works in 2.2.1 and 2.4.0
https://sourceforge.net/p/ncid/discussion/devel/thread/df975b2a/feed.rss does not work in either.

seems to be some different kind of way to login maybe cookie based. does not seem to be supported yet. i try to add it at some point.

**Comment by apstanley** [comment]
We need to be more specific about what works/doesn't work. For example, https://sourceforge.net/blog/feed/ on RSSOwl 2.2.1 works on OSX with Java 1.8.0_121 but doesn't on Windows 10 with Java 1.7.0_51 or jre1.8.0_131. So this points me to a difference in Java on different operating systems. Or something else weird.

**Comment by Xyrio** [comment]
hmm could be. im on win7 with jre8u151

**Comment by taa1** [comment]
I see you've already answered your own question -- fails on 2.2.1 also. Doesn't sound like it will be very easy to solve so thanks for looking into it.

**Comment by Xyrio** [comment]
tried again after some authentication fixes with 2.6.0 and it is "invalid or malformed feed" wich seems to be the same as chrome returns, a html website telling you forbidden (403). no authentication popup of any kind in browser.

if the browser asks for a user and password in a popup window that is basic authentication which is the only one currently supported.

**Comment by Xyrio** [comment]
since 2.8.0 one can use shell:// protocol to call external scripts that provide the rss content.
