### ISSUE TITLE
RSS Fails to Launch (java exit code 13)

### ISSUE THREAD

**Issue by slemay2** [Xyrio/RSSOwlnix#30]
64 bit Windows - trying to launch C:\Program Files\RSSOwlnix\RSSOwlnix.exe first time and I get the error (screenshot and logs attached). I've tried a few things, but gave up - this is 2.6.1. Any suggestions? I'm dumbfounded - thanks.

[1540831870983.log](https://github.com/Xyrio/RSSOwlnix/files/2526224/1540831870983.log)
![capture](https://user-images.githubusercontent.com/44582406/47666338-ae80c300-db79-11e8-89f9-076c0474e5f6.JPG)

**Comment by Xyrio** [comment]
might be if rssowlnix 64bit is started with a java 32bit

**Comment by slemay2** [comment]
Xyrio - you hit it on the head! I just assumed modern day installs of Java were smart enough to install both 32 and 64 bit versions - my fault - I manually installed 64 bit and it started working - thank you for pointing me in that direction!
