### ISSUE TITLE
No sharing to Telegram

### ISSUE THREAD

**Issue by KSGTHB** [Xyrio/RSSOwlnix#33]
When sharing to Telegram will be  work ?

**Comment by Xyrio** [comment]
what is Telegram?

**Comment by KSGTHB** [comment]
I dont  know that sharing to Telegram is  so difficult. In Chrome i see 5 plugins  to share to Telegram
May be you can add sharing by copying name+link to clipboard ?

**Comment by Xyrio** [comment]
if you want name+link share to email and you can copy that.
