### ISSUE TITLE
 Some feeds are not updated

### ISSUE THREAD

**Issue by squromiv** [Xyrio/RSSOwlnix#36]
v.2.6.1 beta. I deleted all news from feeds and continued to use program as usually. Recently I have found out, that some feeds are not updated, but other tools show, that it is wrong.  There is interesting fact: other feeds from the same source are OK. Tried to make "Clean Up" procedure, but nothing changed. It looks like RSSOwlnix can not detect updates of some feeds.

**Comment by Xyrio** [comment]
does the feed show an error? or is it just not detecting changes? do you have a concrete example that can be reproduced?

**Comment by squromiv** [comment]
@Xyrio
I`m really sorry. It was my mistake. Another software, that I use, show wrong date of news publishing to me and I was misled, thinking they are updated. 

Taking this opportunity, can you answer another question? When I add new feed, there is "Delete read news" checkbox in properties, that is checked by default. In global preferences it is turned-off. How to make this option unchecked by default, during creating of new feeds?

**Comment by Xyrio** [comment]
if you deactivate it `Tools/Preferences/Feeds` it should be like that for new feeds at least.

**Comment by squromiv** [comment]
This option in global preferences is deactivated, but after adding of a new feed, it is checked in  feed`s properties by default. 
![screen_Preferences](https://user-images.githubusercontent.com/15985877/49892868-186bd800-fe5b-11e8-95b4-7feef23132b5.jpg)
![screen_Feed Properties](https://user-images.githubusercontent.com/15985877/49893255-10f8fe80-fe5c-11e8-9bf2-7c9e46b108f8.png)

**Comment by Xyrio** [comment]
does it work now? setting/unsetting in global preferences then saving and maybe even restarting can fix such problems sometimes. basically refreshing the configuration somehow.
