### ISSUE TITLE
Search in feed list (only new for example) do not find "old" feeds

### ISSUE THREAD

**Issue by Neustradamus** [Xyrio/RSSOwlnix#41]
Search in feed list (only new for example) do not find "old" feeds, it is not possible to have all in search?

**Comment by Xyrio** [comment]
at the top of the feed tree list is a button "filter state" to show only feeds containing news with the state:  new/unread/stick/erroneous/never visited

**Comment by Neustradamus** [comment]
Yes, I show only "new" but when I search it is only in "new" not in "all" feeds.

**Comment by Xyrio** [comment]
set it back to show all feeds then?

**Comment by Neustradamus** [comment]
If we change the selection "new" instead of "all" to "all", and search again, it is good...
But why not to have a search in all feeds directly in "new" mode?

**Comment by Xyrio** [comment]
because you changed to new mode thats why. then you are supposed to search only in new mode. makes totaly sense. the search is for what is currently visible.
