### ISSUE TITLE
Add a new feed is not same from "File" menu and from the toolbar (with a selected feed)

### ISSUE THREAD

**Issue by Neustradamus** [Xyrio/RSSOwlnix#42]
Add a new feed is not same from "File" menu and from the toolbar (with a selected feed)

For test:
- Have a new feed
- Select a feed in the list (not the last please)
- Add the feed from "File" menu
- Look where it is added

Do same from the toolbar and look where it is added (Comparison).

I think it is same for other "New" actions?

Can you sync for have the same possibility?
The good possibility is from the "File" menu of course.

**Comment by Xyrio** [comment]
i dont understand. when you add a feed it uses what you currently have selected in the feed tree list to look for a folder to use as default. you can still change the target folder.

**Comment by Neustradamus** [comment]
You have not looked where the feed is added!

After the selected feed or at the end of the big big feed list?

**Comment by Xyrio** [comment]
i have looked and the feeds within a folder are sorted by name for me. all 3 ways to add do the same for me.

**Comment by Neustradamus** [comment]
Feeds on the list are old from new and with exceptions -> used the good point (selection of a feed -> File menu -> New -> Feed -> it is added after the selected feed :)

**Comment by Xyrio** [comment]
solved? close issue?

**Comment by Neustradamus** [comment]
no no, we need a solution for have the good process for all:
- When we select (not open) a feed in the list and after add a new feed from toolbar, the feed needs to be added after the selected feed and not at the end of the list (bottom).

**Comment by Xyrio** [comment]
all have the same process, i cannot reproduce what you describe.
