### ISSUE TITLE
Background operations are not showing after corresponding button press

### ISSUE THREAD

**Issue by goaud27** [Xyrio/RSSOwlnix#45]
Just a small bug. When updating feeds there is a green progress bar in the bottom right corner and a button to the right from it: in the original rssowl it was opening "background operations" window, but currently the button press has no action attached to it.

**Comment by Xyrio** [comment]
can still be manually shown using Menu/Tools/Downloads & Activities

**Comment by Xyrio** [comment]
fixed in 2.8.1+

**Comment by bagnaraex** [comment]
where is the download of the 2.8.1+ ?

[]s
Rodrigo César Bagnara
http://about.me/bagnara

**Comment by Xyrio** [comment]
not yet released.

**Comment by Xyrio** [comment]
fixed/improved in 2.9.0
