### ISSUE TITLE
Ctrl+Tab for switching

### ISSUE THREAD

**Issue by larsen0815** [Xyrio/RSSOwlnix#54]
Ctrl+Tab should switch between opened (browser) tabs

**Comment by Xyrio** [comment]
tools/preferences/overview/keys
search for tab or editor there are several ways to switch tabs. i dont know them all so try out what works for you. i changed the shortcuts for next editor and previous editor to switch between feed tabs. they seem to work for embedded browser tabs too.

**Comment by larsen0815** [comment]
I have set "Next Tab" (Category: RSSOwlnix) to "Ctrl+Tab" and "Previous Tab" to "Ctrl+Shift+Tab". The default ones "Ctrl+PgUp/PgDown" work too. afaik, users are more used to "Ctrl+Tab" from their browsers, so maybe this should be the default for new installations.
