### ISSUE TITLE
This article does not provide any content

### ISSUE THREAD

**Issue by Joel889** [Xyrio/RSSOwlnix#56]
Add the following feed:
https://feeds.a.dj.com/rss/RSSWSJD.xml

Other RSS readers show a few lines of text as expected.
RSSOwlnix 2.7 (as well as the original RSSOwl) show "This article does not provide any content."

**Comment by Xyrio** [comment]
seems like the content of the `<description>` tag is not shown if it is `<![CDATA[ ]]>`

**Comment by larsen0815** [comment]
Happens with https://xyrio.github.io/RSSOwlnix-site/updates.rss in RSSOwlnix 2.8.0 as well.
Probably displaying the correct content after hitting "Attempt to download and display the article content."

**Comment by Xyrio** [comment]
Attempt to download... uses the link to download content. thats a different feature.

**Comment by Xyrio** [comment]
fixed in 2.9.0
