### ISSUE TITLE
Says I don't I have Java but I do	

### ISSUE THREAD

**Issue by ackern** [Xyrio/RSSOwlnix#63]
When I try to install RSSOwlnix or run my old RSSOwl it says my computer doesn't have Java but I do. RSSOwl always used to run fine for me and I have no idea why this is happening.
![x2scrap](https://user-images.githubusercontent.com/8440262/61511693-d2ca4b80-a9f7-11e9-814b-0293b62d350e.png)

![x2scrap](https://user-images.githubusercontent.com/8440262/61511738-f7262800-a9f7-11e9-9287-2cdba81ec6e8.png)

**Comment by Xyrio** [comment]
you either need java be available in your PATH environment variable or in a subfolder like your image is showing.
the latest java 12 is supported try downloading the zip from oracle and unzip it so the following exists: `RSSOwlnix\jre\bin\javaw.exe`
