### ISSUE TITLE
Where is my directory of subscribed feeds?

### ISSUE THREAD

**Issue by Anselm970** [Xyrio/RSSOwlnix#65]
Hello, I am just moving from my old computer with Windows 7 to a new one with Windows 10. On the old one I had RSSOwl installed. When I wanted to download the latest version for the reinstall, I realized that there is now RSSOwlnix. I could install this program and import the data perfectly, I have only one very simple problem, but can not find a solution. I had configured RSSOwl so that in the layout "widescreen" three columns were displayed: On the left a directory with folders of the subscribed feeds. In the middle a table of contents of the respective feed with title, date, author etc. And on the right a preview of the feeds content. With RSSOwlnix I just can not manage to display the left column. Please help. Thanks in advance and greetings, Anselm

**Comment by Xyrio** [comment]
in the menu activate `View / Feeds` then drag the Feed tab to the left of the window.

**Comment by Anselm970** [comment]
Thank you so much! Anselm

**Comment by Xyrio** [comment]
i asume the problem is solved then.
