### ISSUE TITLE
Use Proxy For Builtin Web Browser options disapeared in preferences

### ISSUE THREAD

**Issue by war59312** [Xyrio/RSSOwlnix#67]
Hi,

Call me crazy, or the option to use a proxy with the builtin web browser has gone missing.

Can that please be added back?

Thanks,

Will

**Comment by Xyrio** [comment]
indeed it disappeared. the proxy settings in windows internetoptions are also not used i asume.

**Comment by Xyrio** [comment]
will be fixed in 2.8.1

**Comment by Xyrio** [comment]
fixed in 2.9.0
