### ISSUE TITLE
Almost no feed works after moving to a PC with Windows 10

### ISSUE THREAD

**Issue by Anselm970** [Xyrio/RSSOwlnix#69]
Hello,

I moved from a Windows 7 PC to a Windows 10 Pro 64 bit one. I exported RSSOwl like described in the FAQ to a rssowl.opml file and imported it into RSSOwlnix. I have subscribed about 30 regular feeds and 10 newsgroups (Usenet). Nine feeds are shown like before, the others not. The status of the most regular feeds is "The last attempt to load this feed failed for an unknown reason." The status of all newsgroup feeds is "The last attempt to load this feed failed. Reason: Unsupported Communication Protocol 'news'".

Another question: I would like to switch RSSOwlnix to German like RSSOwl. Using the parameter -nl de fails. Does RSSOwlnix provide German?

Thank you in advance, Anselm

**Comment by Xyrio** [comment]
to get german you need to install the nls addon for german, if your os is german it will automatically choose german. 

menu `Help / install new software`
choose the url that ends with /nls
checkbox `groupy items by category = off`


since i dont have/use window 10 i cannot test it (win7 here).

**Comment by Anselm970** [comment]
Hello and thank you. Unfortunately it does not work here. I recorded a video of my approach and took a screenshot of my feeds:

http://xa4151.xa4.serverdomain.org/12/rss.htm

**Comment by Xyrio** [comment]
attach the logfile from: menu / help / export logfile here. otherwise i have no clue.

**Comment by Anselm970** [comment]
Here it is:
[rssowl.log](https://github.com/Xyrio/RSSOwlnix/files/3619990/rssowl.log)

**Comment by Xyrio** [comment]
i tried it on windows 10 1809 enterprise 64bit (DE), openjdk 12. german nls plugin works. newsgroup ( `news://News.Individual.DE/muc.misc` ) seems to work too. i get the password prompt but i dont have newsgroup accounts. are your win10 updates up to date?

rename the `%userprofile%\.rssowlnix-beta` folder and try fresh. dont use opml just add one newsgroup link. maybe you get different results.

i see from the log you use java 8 64bit, you could try oracle jdk 12 or open jdk 12. maybe it is some java weirdness on win10.
put a jdk inside the rssowl folder, you can download the zip and unzip it so the following paths exist:
`RSSOwlnix/RSSOwlnix.exe`
`RSSOwlnix/jre/bin/java.exe`

**Comment by Xyrio** [comment]
another idea, try running as administrator (right click on rssowlnix.exe ...)

**Comment by Anselm970** [comment]
In the meantime I renamed the directory .rssowlnix-beta and installed the software for German and for feeds successfully. The German language works now. Also, I can now retrieve the _newsgroup_ feeds after the user ID and password have been queried. The feeds of Wikipedia still work.
Feeds from this link work:
http://www.bayern-evangelisch.de/www/startseite_rss.rss
Feeds from this link do not work:
If I here ...
https://www.sonntagsblatt.de/
... click on "subscribe" (far below besides the feeds icon), RSSOwlnix opens, but there is no new feed.
Running as an administrator does not change anything (even with the old one
directory .rssowlnix-beta). I had hoped to be able to move RSSOwl(nix) by exporting and importing. I attach the log file from the current state.
[rssowl_2019-09-19.log](https://github.com/Xyrio/RSSOwlnix/files/3630337/rssowl_2019-09-19.log)

**Comment by Xyrio** [comment]
export/import does not copy news data. instead you can move the whole database over. the database is in `.rssowlnix-beta\.metadata\.plugins\org.rssowl.core`. be sure to remove all new files and copy all old files within the *core directory

the sonntagsblatt rss works. you can just copy the link of the subscribe button and add it manually to rssowl if it otherwise doesnt work.

the feedhandler plugin requires you to run rssowl as admin at least once so it can register:
(in log around bottom this error appears if it cannot)
`java.io.IOException: Cannot run program "C:\Users\Anselm Rapp\.rssowlnix-beta\.metadata\.plugins\org.rssowl.contrib.feedhandler\register_rssowl.exe": CreateProcess error=740, Der angeforderte Vorgang erfordert erhöhte Rechte
`

**Comment by Anselm970** [comment]
Success. I set up all the feeds new and copied the links manually.

Thanks for your help, Anselm
