### ISSUE TITLE
Feeds not imported from 2.2.1

### ISSUE THREAD

**Issue by awiebe** [Xyrio/RSSOwlnix#7]
I can export from 2.2.1 and reimport OMPL, but then I have to go through my feeds and mark all the things I've read again.  This wouldn't be such a big deal if I just used RSSowl for news, but I tend to use it for comics, so this is quite a pain.

**Comment by Xyrio** [comment]
you can manually copy the db from 2.2.1 over. on the release page is a short howto.

**Comment by awiebe** [comment]
Ah I see it now. Thanks this did the trick.

**N.B.** If you didn't do this before first run, delete the existing `~/rssowl2-beta` before copying the old data, or the files therein will prevent this restore from working properly.

For anybody else reading this under *NIX, here's a nice oneliner.
```
rm -rf "~/.rssowl2-beta ; cp -R "~/.rssowl2" "~/.rssowl2-beta"
```
