### ISSUE TITLE
Change to open news in external browser per folder

### ISSUE THREAD

**Issue by heartlessglasses** [Xyrio/RSSOwlnix#72]
Would it be possible to have an option to change the browser used for opening sites on a per-folder basis? I set it to open news where the content is empty in the browser and I want to use an external browser for one specific feeds folder, but use the embedded browser for other folders.
Either way, thank you for all the hard work!

**Comment by Xyrio** [comment]
not necessary. just right click the news and choose open in external browser or drag and drop the news into any browser window.
