### ISSUE TITLE
RSSOwlnix crashes every time when running the clean up process (higher memory requirement)

### ISSUE THREAD

**Issue by Echtze1t** [Xyrio/RSSOwlnix#76]
[rssowl.log](https://github.com/Xyrio/RSSOwlnix/files/3935431/rssowl.log)

Hello there.

first of all, thank you so much for keeping this program alive. It is a central part of my life (I'm not even kidding) and I don't know what I would do without it. There's only one other RSS client out there, but it's missing some features that I depend on.

The problem I have is with the database clean up process (Tools > Clean Up). It crashes on the same spot every time. I had this problem before with the old RSSOwl and my guess is, the number of entries is just too big for the program to handle.

I know where the problem stems from, I'm adding this info in hopes that it is helpful. I have two feeds, that grow pretty big after a month if left to their own devices. There was a time when I didn't know this would be a problem and when I discovered it, it was already too late to fix properly.

See, the problem is, even though I set a limit of items AND a time limit to keep entries, RSSOwl doesn't always follow these rules (why I don't know). If one of the two limits is breached, you first have to click the feed, and only then will RSSOwl begin deleting the entries that go beyond that limit.

But the last time it didn't work this way and the program crashed. I had to delete the whole feed, but I'm pretty sure the entries still remain in the database. I subscribed to the same feed again and everything is working fine, except for the clean up process.

I've included the log file you can create when the error happens and I'd just like to know if it is fixable or if I can repair my DB some other way maybe?

**Comment by karnak-ID** [comment]
Increasing heap file might help. In RSSOwlnix.ini the default is set to -Xmx192m and for example you could try to set it at -Xmx4096m.

**Comment by Echtze1t** [comment]
> Increasing heap file might help. In RSSOwlnix.ini the default is set to -Xmx192m and for example you could try to set it at -Xmx4096m.

What do you know, that actually worked. Thank you so much!

My current DB shrunk a whopping 500MB after the successful clean up. Is there a way to control when backups are made or can you even make one manually?

Does the increased heap file size impact the running program in some way, i.e. does is use more RAM now?

**Comment by Xyrio** [comment]
backups are made quite often upto 1 week see the rssowl.db* files in `%userprofile%\.rssowlnix-beta\.metadata\.plugins\org.rssowl.core\`. manually resotring backups involves renaming one of the other files to rssowl.db

yes most of the time it uses more ram. more ram can increase speed too. roughly having ram be around two times the size of your rssowl.db file should be enough. cleanup involves copying stuff in memory.

**possible improvement**: try to keep less data in memory on cleanup to reduce necessary memory size.
