### ISSUE TITLE
apt

### ISSUE THREAD

**Issue by 030** [Xyrio/RSSOwlnix#77]
What about creating a debian package so that it is possible to install RSSOwlnix by issuing ```apt install -y rssownlnix```?

**Comment by Xyrio** [comment]
up to someone else i wont do that.

**Comment by 030** [comment]
Ansible role created https://github.com/030/ansible-rssowlnix

**Comment by 030** [comment]
@Xyrio Perhaps you could add a link to the README?

**Comment by Xyrio** [comment]
added to readme

**Comment by Albirew** [comment]
Hello, just to say the ansible-rssowlnix repo has been deleted.
