### ISSUE TITLE
question: redirect authentication flow

### ISSUE THREAD

**Issue by johr** [Xyrio/RSSOwlnix#80]
I wan't to access a rss-feed that needs authentication. the authentication is done using a redirect to a login page to provide the credentials and further calling back the previously requested page. this is some custom process, not using OAuth.... or some similar scheme. 
do you have any hints on how to handle this case?

**Comment by Xyrio** [comment]
a) use some script that does the login and downloads the rss file periodically then point at the file ie: `file:///c:/myfolder/myrss.xml
b) write a simple rest web service that can hanlde the special way to login and provides the rss like a proxy.

**Comment by johr** [comment]
thanks, I will give it a try. adding results in a few days if I had success.

**Comment by Xyrio** [comment]
since 2.8.0 one can use shell:// protocol to call external scripts that provide the rss content.
