### ISSUE TITLE
Feeds with passwords

### ISSUE THREAD

**Issue by hajo62** [Xyrio/RSSOwlnix#84]
How would I debug why I get a 403 for a password protected (intranet) feed, although I have entered the credentials in the settings?

**Comment by Xyrio** [comment]
- run rssowlnix from eclipse and debug using eclipse
- use wireshark or other network snifferes
- use a small web proxy that you debug on so you can see traffic

**Comment by Xyrio** [comment]
since rssowlnix has no cookies, it behaves every time like the first visit to a page so doing the same in any browser after clearing cookies/caches could also help.

since 2.8.0 one can use shell:// protocol to call external scripts that provide the rss content.
