### ISSUE TITLE
Error message and instable program after windows crash

### ISSUE THREAD

**Issue by Echtze1t** [Xyrio/RSSOwlnix#87]
Hello,

I had a BSOD yesterday for the first time in maybe five years (Windows 8.1). Since then, RSSOwl is running unstable. First it wouldn't start at all and now it just randomly crashes without warning.

I tried to fix it with re-installing all the files. I also did a cleanup, which runs through, but when it is started, the following error pops up:

![Untitled](https://user-images.githubusercontent.com/25301944/81158451-47bb4180-8f88-11ea-9476-fb73aa2f8a03.png)

**Comment by Xyrio** [comment]
the messages clearly tells you that it cannot write to the harddisk for some reason. by default it writes to stuff under `%userprofile%\.rssowlnix-beta`. so make sure that is possible.

**Comment by Echtze1t** [comment]
The folder and the HDD are both writable just fine. This only happened after the crash, so it is directly connected. My guess is, that one or more files were corrupted. I thought maybe you could tell by that error message.

Can I send you a log file or something else?

**Comment by Xyrio** [comment]
i doubt ill figure out the reason, try a fresh start and then replace the new db with the old one.
like i described in #85.

**Comment by Xyrio** [comment]
maybe on a crash it takes a while for the program to end. if were to restart to fast the old one would still be running. try checking in taskmanager how long it takes for it to close after you close the crash window.
