### ISSUE TITLE
Deleted items do not return with updates

### ISSUE THREAD

**Issue by Jeminator** [Xyrio/RSSOwlnix#88]
In RSSOwlnix, when i delete an item by accident, clicking "Update all" does not replace the deleted item in my feed.
The deleted item still exists in my source RSS. 
How do i get back the deleted item ? - Other than Undo. Thanks

**Comment by Xyrio** [comment]
you can undo immediately after. otherwise the deletion is remembered until you do cleanup. thats when it truly gets removed. maybe after cleanup if you do an update it comes back, if it is still in the rss but im not sure. try it out.
