### ISSUE TITLE
Customise Number of Articles shown in Newpaper layout

### ISSUE THREAD

**Issue by SethBodine** [Xyrio/RSSOwlnix#91]
Currently there are 5 Options (10,25,50,100,All), is there a chance larger numbers such as 250, and 500, or ideally a free value field could be added (either via the config file, or in the UI)?

**Comment by Xyrio** [comment]
100 is already pretty big but it could be changed to just a custom number or 0 meaining off/all

**Comment by Xyrio** [comment]
fixed in 2.8.1+

**Comment by Xyrio** [comment]
improved in 2.9.0
