### ISSUE TITLE
Share news to "Bibsonomy" 

### ISSUE THREAD

**Issue by hartridge** [Xyrio/RSSOwlnix#95]
"Bibsonomy" is a free social bookmark and publication sharing system. It is offered by the KDE group of the University of Kassel, the DMIR group of the University of Würzburg, and the L3S Research Center, Germany.

It would be nice to implement "Bibsonomy" in the "Share news"-section. Btw. "Mister Wong" doesn´t exist anymore for social-boomarking...

thanks in advance :-)

**Comment by Xyrio** [comment]
it seems to use http post form but only get links are supported currently. no idea how to implement right now.

**Comment by hartridge** [comment]
HiThanks for Your fast response!For Firefox there is an AddOn called "BibSonomy Buttons" Maybe this info helps? Regards RichardP.s. I am not a software developer, have absolut no experience in programming ;-)-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 01.07.20, 02:20 schrieb Xyrio <notifications@github.com>:

   
  it seems to use http post form but only get links are supported currently. no idea how to implement right now.

**Comment by Xyrio** [comment]
plugin uses this: `https://www.bibsonomy.org/ShowBookmarkEntry?selection=SELECTION&url=URL&referer=REFERER&description=DESC&abstractGrouping=public&autoLogin=true`

**Comment by Xyrio** [comment]
added to 2.9.0
