### ISSUE TITLE
exporting data to csv

### ISSUE THREAD

**Issue by Koinokalo** [Xyrio/RSSOwlnix#97]
Volevo sapere se qualcuno è in grado di aggiungere delle nuove funzionalità al programma. In particolare la possibilità di esportare in un file CSV tutti i dati dei feed mediante selezione singola.
Aggiungere al MENU "Condividi" la voce export CSV e consentire di selezionare i campi da esportare (Gli stessi presenti nelle preferenze).
Aggiungere il link alla immagine.

Per chi fosse interessato anche con contributo può contattarmi a
giovanni.erra@koinokalo.it

Grazie

**Comment by ErikBrown2** [comment]
Daar ben ik het helemaal mee eens. Maybe it would be handy to use English?

**Comment by Koinokalo** [comment]
Sorry,
do you think we can make this change to the software?
How long does it take?
how much could it cost?
Do you need any more information?

You can contact me at any time.

Il giorno lun 17 ago 2020 alle ore 16:03 ErikBrown2 <
notifications@github.com> ha scritto:

**Comment by Xyrio** [comment]
i dont understand that language, explain in english.

**Comment by Koinokalo** [comment]
Good morning,
I use a translator to speak from Italian to English.
I am looking for someone interested in adding a new feature to the program.
I would like to be able to export all feed details to a CVS format file.
Also, I would need to add other fields to the output file.
I would like to be able to add tags or other information that I can
download as output.
If necessary, I can produce a detailed document.
Is there anyone who could help me?

Thanks and sorry for the inconvenience.

Il giorno lun 17 ago 2020 alle ore 23:03 Xyrio <notifications@github.com>
ha scritto:

**Comment by Xyrio** [comment]
well tags are called labels in rssowlnix. do you want to import the csv file into excel or what?

**Comment by Koinokalo** [comment]
I would like to export all the data of the item to a CSV file.
If possible, I would like to add other fields that are filled in manually
when I see the item. For example, I would like to add some notes or an
additional text.
I can produce a document with the changes to be made.
What language is used to write the program?
I know VB and C ++

Il giorno mer 19 ago 2020 alle ore 01:24 Xyrio <notifications@github.com>
ha scritto:

**Comment by Xyrio** [comment]
the program is written in java and uses eclipse rcp.
well the existing csv export could be extended to also export the description and labels.
for custom notes there is the notes addon, but how to grab that data optionally one has to figure out first.

overall it should be possible but this has no priority for me. if it turns out to be easy i might do it but again no promises.

**Comment by Koinokalo** [comment]
I can pay up to 100 euros for the changes.
I can produce a document with requests for changes.
Where can I get the addon?
This is my email:
giovanni.erra
@
koinokalo.it

Grazie :-)

Il giorno mer 19 ago 2020 alle ore 20:34 Xyrio <notifications@github.com>
ha scritto:

**Comment by Xyrio** [comment]
i dont take donations.

**Comment by Xyrio** [comment]
https://github.com/Xyrio/RSSOwlnix/wiki/How-To-Install-Addons-or-Translations

**Comment by Xyrio** [comment]
after further investigation, this is already possible. it will export a feed depending on what is visible in gui table view.
for example 
- use classic view for news
- change the visible columns from menu: View / Columns (and activate link column if needed)
- while a feed is active and its news are visible
- go menu: File / Save As / *.csv

if you dont like the default csv separator `;` u ca provide it as a java system variable (on rssowlnix start or put it in the rssowlnix.ini as a new line after the -vmargs line, see also https://github.com/Xyrio/RSSOwlnix/wiki/FAQ#item_9 )  with -DcsvSeparator=\\t
